{
 "title": "Chest X-Ray Prediction Dashboard",
 "tags": [
  "xray",
  "mlops"
 ],
 "refresh": "10s",
 "panels": [
  {
   "title": "Total Predictions",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(xray_requests_total{status='success'})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Avg Latency (s)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(xray_request_latency_seconds_sum[5m]) / rate(xray_request_latency_seconds_count[5m])",
     "legendFormat": "Latency"
    }
   ]
  },
  {
   "title": "Pneumonia Detections",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "xray_predictions_total{prediction='PNEUMONIA'}",
     "legendFormat": "Pneumonia"
    }
   ]
  },
  {
   "title": "Normal Results",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "xray_predictions_total{prediction='NORMAL'}",
     "legendFormat": "Normal"
    }
   ]
  },
  {
   "title": "Request Rate (per minute)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "rate(xray_requests_total[1m]) * 60",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Prediction Latency over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "targets": [
    {
     "expr": "rate(xray_request_latency_seconds_sum[5m]) / rate(xray_request_latency_seconds_count[5m])",
     "legendFormat": "Avg Latency"
    }
   ]
  }
 ]
}